apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Adjust based on the frontend app’s container port
  type: LoadBalancer  # Exposes frontend externally via a cloud provider LB
